---
- name: Install and configure NGINX
  hosts: host2
  become: true
  vars:
    nginx_listen_port: 8080

  tasks:

   - name: stop firewalld
     systemd:
       name: firewalld
       state: stopped
       enabled: no

   - name: Install EPEL Repo package from standard repo
     yum:
      name: epel-release
      state: present
     tags:
        - epel-package
        - packages

   - name: Install nginx package from epel repo
     yum:
      name: nginx
      state: latest
     notify:
      - restart nginx
     tags:
      - nginx-package
      - packages

   - name: Create NGINX config file from template
     template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
     notify:
      - reload nginx
     tags:
      - nginx-configuration

  handlers:
    
   - name: restart nginx
     systemd:
       name: nginx
       state: restarted
       enabled: yes

   - name: reload nginx
     systemd:
       name: nginx
       state: reloaded