---
- name: Playbook to configure IPA clients with username/password
  hosts: freeipa-client
  become: yes
  gather_facts: true

  vars:

    ipa_domain: otus.local
    ipa_realm: OTUS.LOCAL
    ipa_admin: admin
    ipa_admin_pass: otusotus
    ipa_server: freeipa-server.otus.local

  tasks:

   - name: Install EPEL Repo package from standard repo
     yum:
      name: epel-release
      state: present
     tags:
      - epel-package
      - packages
  
   - name: Install ipa-client
     yum:
       name: ipa-client
       state: present
     tags:
      - install_ipa-client
    
   - name: Configure ipa-client
     shell: ipa-client-install -U
      --domain {{ ipa_domain }}
      --principal {{ ipa_admin }}@{{ ipa_realm }}
      --password {{ ipa_admin_pass }}
      --server {{ ipa_server }}
      --realm {{ ipa_realm }}
      --force-join
      --mkhomedir
     tags:
       - configure_ipa-client
