---
- name: Playbook to configure IPA servers with username/password
  hosts: freeipa-server
  become: yes
  gather_facts: true

  vars:

    ipa_domain: otus.local
    ipa_realm: OTUS.LOCAL
    ipa_admin: admin
    ipa_admin_pass: otusotus
    ipa_server: freeipa-server.otus.local

  tasks:

   - name: Install EPEL Repo package from standard repo
     yum:
      name: epel-release
      state: present
     tags:
      - epel-package
      - packages

   - name: Install FreeIPA server
     yum:
       name: ipa-server
       state: present
     tags:
      - install_ipa-server
    
   - name: Configure ipa-server
     shell: ipa-server-install -U
      --hostname={{ ipa_server }}
      --domain={{ ipa_domain }}
      --realm={{ ipa_realm }}
      --ds-password={{ ipa_admin_pass }}
      --admin-password={{ ipa_admin_pass }}
     notify:
      - restart ipa services
     tags:
      - configure_ipa-server

  handlers:
    
   - name: restart ipa services
     systemd:
       name: ipa
       state: restarted
       enabled: yes
       