# -*- mode: ruby -*-
# vim: set ft=ruby :

home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :pam => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :ip_addr => '192.168.11.101',
  },
}

Vagrant.configure("2") do |config|

    config.vm.box_version = "1804.02"
    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "256"]
                    needsController = false
            end
            box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            yum install -y epel-release
            yum install -y pam_script nc
            useradd day
            useradd friday
            echo "Otus2019" | sudo passwd --stdin day
            echo "Otus2019" | sudo passwd --stdin friday
            groupadd admin
            usermod -aG admin day
            cp /vagrant/sshd /etc/pam.d/
            cp /vagrant/login /etc/pam.d/
            cp /vagrant/capability.conf /etc/security/
            setcap cap_net_bind_service=ei /usr/bin/ncat
#            cp /vagrant/su /etc/pam.d/
#            cp /vagrant/pam_script /etc/
#            systemctl restart sshd
         SHELL
        end
    end
  end
  
